/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OffScenePanelBeanForm.java
 *
 * Created on 10/12/2010, 17:28:42
 */

package com.jme3.gde.jmeguiforms;

import com.jme3.gde.core.scene.OffScenePanel;

/**
 *
 * @author Glauco
 */
public class OffScenePanelBeanForm extends OffScenePanel {

    /** Creates new form OffScenePanelBeanForm */
    public OffScenePanelBeanForm() {
        this(320,320);
    }

    /** Creates new form OffScenePanelBeanForm */
    public OffScenePanelBeanForm(int width, int height) {
        super(width, height);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 51, 51));
        setCamFocus(null);
        setPreferredSize(new java.awt.Dimension(320, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
