/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WheelPanelBeanForm.java
 *
 * Created on 13/12/2010, 13:04:17
 */
package com.jme3.gde.jmeguiforms;

import com.jme3.gde.jmeguiforms.event.WheelPanelEvent;
import com.jme3.gde.jmeguiforms.event.WheelPanelListener;
import com.jme3.math.Vector3f;
import java.util.ArrayList;
import java.util.List;
import org.jdesktop.swingx.JXTextField;
import org.jdesktop.swingx.JXTitledPanel;

/**
 *
 * @author Glauco
 */
public class WheelPanel extends JXTitledPanel {

    private List<WheelPanelListener> listeners;

    /** Creates new form WheelPanelBeanForm */
    public WheelPanel() {
        initComponents();
        listeners = new ArrayList<WheelPanelListener>();
    }

    public void addWheelPanelListener(WheelPanelListener listener) {
        listeners.add(listener);
    }

    public void removeWheelPanelListener(WheelPanelListener listener) {
        listeners.remove(listener);
    }

    public void setSpatialValue(String spatial) {
        spatialTextField.setText(spatial);
    }

    public String getSpatialValue() {
        return spatialTextField.getText();
    }

    public WheelPanel setNameValue(String name) {
        ((JXTextField) getLeftDecoration()).setText(name);
        return this;
    }

    public String getNameValue() {
        return ((JXTextField) getLeftDecoration()).getText();
    }

    public void setConnectionPointValue(Vector3f connectionPoint) {
        jSpinner1.setValue(connectionPoint.x);
        jSpinner2.setValue(connectionPoint.y);
        jSpinner3.setValue(connectionPoint.z);
    }

    public Vector3f getConnectionPointValue() {
        return new Vector3f(
                (Float) jSpinner1.getValue(),
                (Float) jSpinner2.getValue(),
                (Float) jSpinner3.getValue());
    }

    public void setDirectionValue(Vector3f direction) {
        jSpinner4.setValue(direction.x);
        jSpinner5.setValue(direction.y);
        jSpinner6.setValue(direction.z);
    }

    public Vector3f getDirectionValue() {
        return new Vector3f(
                (Float) jSpinner4.getValue(),
                (Float) jSpinner5.getValue(),
                (Float) jSpinner6.getValue());
    }

    public void setAxleValue(Vector3f axle) {
        jSpinner7.setValue(axle.x);
        jSpinner8.setValue(axle.y);
        jSpinner9.setValue(axle.z);
    }

    public Vector3f getAxleValue() {
        return new Vector3f(
                (Float) jSpinner7.getValue(),
                (Float) jSpinner8.getValue(),
                (Float) jSpinner9.getValue());
    }

    public void setRestLengthValue(float restLength) {
        jSpinner10.setValue(restLength);
    }

    public float getRestLengthValue() {
        return (Float) jSpinner10.getValue();
    }

    public void setRadiusValue(float radius) {
        jSpinner11.setValue(radius);
    }

    public float getRadiusValue() {
        return (Float) jSpinner11.getValue();
    }

    public void setFrontWheelValue(boolean frontWheel) {
        jXComboBox1.setSelectedItem(Boolean.toString(frontWheel));
    }

    public boolean isFrontWheelValue() {
        return Boolean.parseBoolean((String) jXComboBox1.getSelectedItem());
    }

    public void cleanup() {
        listeners.clear();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new org.jdesktop.swingx.JXButton();
        nameTextField = new org.jdesktop.swingx.JXTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jXTaskPane3 = new org.jdesktop.swingx.JXTaskPane();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jXTaskPane4 = new org.jdesktop.swingx.JXTaskPane();
        jSpinner10 = new javax.swing.JSpinner();
        jXTaskPane5 = new org.jdesktop.swingx.JXTaskPane();
        jSpinner11 = new javax.swing.JSpinner();
        jXTaskPane6 = new org.jdesktop.swingx.JXTaskPane();
        jXComboBox1 = new org.jdesktop.swingx.JXComboBox();
        jXTaskPane7 = new org.jdesktop.swingx.JXTaskPane();
        spatialTextField = new org.jdesktop.swingx.JXTextField();
        loadSpatialButton = new org.jdesktop.swingx.JXButton();

        closeButton.setText(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.closeButton.text")); // NOI18N
        closeButton.setContentAreaFilled(false);
        closeButton.setFont(new java.awt.Font("Lao UI", 1, 11));
        closeButton.setRequestFocusEnabled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        nameTextField.setText(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.nameTextField.text")); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        setLeftDecoration(nameTextField);
        setRightDecoration(closeButton);
        getContentContainer().setLayout(new java.awt.GridLayout(1, 0));

        jXTaskPane1.setCollapsed(true);
        jXTaskPane1.setTitle(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.jXTaskPane1.title")); // NOI18N
        jXTaskPane1.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), null, null, Float.valueOf(1.0f)));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jSpinner1);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), null, null, Float.valueOf(1.0f)));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jSpinner2);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(2.0f), null, null, Float.valueOf(1.0f)));
        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });
        jXTaskPane1.getContentPane().add(jSpinner3);

        jXTaskPaneContainer1.add(jXTaskPane1);

        jXTaskPane2.setCollapsed(true);
        jXTaskPane2.setTitle(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.jXTaskPane2.title")); // NOI18N
        jXTaskPane2.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(1.0f)));
        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });
        jXTaskPane2.getContentPane().add(jSpinner4);

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(-1.0f), null, null, Float.valueOf(1.0f)));
        jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner5StateChanged(evt);
            }
        });
        jXTaskPane2.getContentPane().add(jSpinner5);

        jSpinner6.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(1.0f)));
        jSpinner6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner6StateChanged(evt);
            }
        });
        jXTaskPane2.getContentPane().add(jSpinner6);

        jXTaskPaneContainer1.add(jXTaskPane2);

        jXTaskPane3.setCollapsed(true);
        jXTaskPane3.setTitle(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.jXTaskPane3.title")); // NOI18N
        jXTaskPane3.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jSpinner7.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(-1.0f), null, null, Float.valueOf(1.0f)));
        jSpinner7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner7StateChanged(evt);
            }
        });
        jXTaskPane3.getContentPane().add(jSpinner7);

        jSpinner8.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(1.0f)));
        jSpinner8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner8StateChanged(evt);
            }
        });
        jXTaskPane3.getContentPane().add(jSpinner8);

        jSpinner9.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), null, null, Float.valueOf(1.0f)));
        jSpinner9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner9StateChanged(evt);
            }
        });
        jXTaskPane3.getContentPane().add(jSpinner9);

        jXTaskPaneContainer1.add(jXTaskPane3);

        jXTaskPane4.setCollapsed(true);
        jXTaskPane4.setTitle(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.jXTaskPane4.title")); // NOI18N
        jXTaskPane4.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jSpinner10.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), null, null, Float.valueOf(1.0f)));
        jSpinner10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner10StateChanged(evt);
            }
        });
        jXTaskPane4.getContentPane().add(jSpinner10);

        jXTaskPaneContainer1.add(jXTaskPane4);

        jXTaskPane5.setCollapsed(true);
        jXTaskPane5.setTitle(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.jXTaskPane5.title")); // NOI18N
        jXTaskPane5.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jSpinner11.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), null, null, Float.valueOf(1.0f)));
        jSpinner11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner11StateChanged(evt);
            }
        });
        jXTaskPane5.getContentPane().add(jSpinner11);

        jXTaskPaneContainer1.add(jXTaskPane5);

        jXTaskPane6.setCollapsed(true);
        jXTaskPane6.setTitle(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.jXTaskPane6.title")); // NOI18N
        jXTaskPane6.getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jXComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "True", "False" }));
        jXComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXComboBox1ActionPerformed(evt);
            }
        });
        jXTaskPane6.getContentPane().add(jXComboBox1);

        jXTaskPaneContainer1.add(jXTaskPane6);

        jXTaskPane7.setCollapsed(true);
        jXTaskPane7.setTitle(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.jXTaskPane7.title")); // NOI18N
        jXTaskPane7.getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        spatialTextField.setEditable(false);
        spatialTextField.setText(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.spatialTextField.text")); // NOI18N
        spatialTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spatialTextFieldActionPerformed(evt);
            }
        });
        jXTaskPane7.getContentPane().add(spatialTextField);

        loadSpatialButton.setText(org.openide.util.NbBundle.getMessage(WheelPanel.class, "WheelPanel.loadSpatialButton.text")); // NOI18N
        loadSpatialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSpatialButtonActionPerformed(evt);
            }
        });
        jXTaskPane7.getContentPane().add(loadSpatialButton);

        jXTaskPaneContainer1.add(jXTaskPane7);

        jScrollPane1.setViewportView(jXTaskPaneContainer1);

        getContentContainer().add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner3StateChanged

    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner4StateChanged

    private void jSpinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner5StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner5StateChanged

    private void jSpinner6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner6StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner6StateChanged

    private void jSpinner7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner7StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner7StateChanged

    private void jSpinner8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner8StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner8StateChanged

    private void jSpinner9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner9StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner9StateChanged

    private void jSpinner10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner10StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner10StateChanged

    private void jSpinner11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner11StateChanged
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jSpinner11StateChanged

    private void jXComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXComboBox1ActionPerformed
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_jXComboBox1ActionPerformed

    private void spatialTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spatialTextFieldActionPerformed
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_spatialTextFieldActionPerformed

    private void loadSpatialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSpatialButtonActionPerformed
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.loadAssetActionPerformed(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_loadSpatialButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.closeActionPerformed(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
        for (WheelPanelListener wheelPanelListener : listeners) {
            wheelPanelListener.valueChanged(new WheelPanelEvent(this));
        }
    }//GEN-LAST:event_nameTextFieldActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton closeButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private org.jdesktop.swingx.JXComboBox jXComboBox1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane3;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane4;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane5;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane6;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane7;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private org.jdesktop.swingx.JXButton loadSpatialButton;
    private org.jdesktop.swingx.JXTextField nameTextField;
    private org.jdesktop.swingx.JXTextField spatialTextField;
    // End of variables declaration//GEN-END:variables
}
