/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WheelPanelContent.java
 *
 * Created on 20/12/2010, 22:04:16
 */
package com.jme3.gde.jmeguiforms;

import com.jme3.gde.jmeguiforms.event.WheelPanelListener;
import java.util.Arrays;

/**
 *
 * @author Glauco
 */
public class WheelPanelContent extends javax.swing.JPanel {

    /** Creates new form WheelPanelContent */
    public WheelPanelContent() {
        initComponents();
    }

    public WheelPanel addWheelPanel(String wheelName) {
        WheelPanel panel = new WheelPanel().setNameValue(wheelName);
        jXPanel1.add(panel);
        jXPanel1.validate();
        jXPanel1.repaint();
        return panel;
    }

    public void removeWheelPanel(String wheelName) {
        for (WheelPanel wheelPanel : Arrays.asList((WheelPanel[]) getComponents())) {
            if (wheelPanel.getNameValue().equals(wheelName)) {
                remove(getWheelPanel(wheelName));
            }
        }
    }

    public WheelPanel getWheelPanel(String wheelName) {
        for (WheelPanel wheelPanel : Arrays.asList((WheelPanel[]) getComponents())) {
            if (wheelPanel.getNameValue().equals(wheelName)) {
                return wheelPanel;
            }
        }
        return null;
    }

    public void addWheelPanelListener(WheelPanelListener listener) {
        for (WheelPanel wheelPanel : Arrays.asList((WheelPanel[]) getComponents())) {
            wheelPanel.addWheelPanelListener(listener);
        }
    }

    public void cleanup() {
        for (WheelPanel wheelPanel : Arrays.asList((WheelPanel[]) getComponents())) {
            wheelPanel.cleanup();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXButton1 = new org.jdesktop.swingx.JXButton();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();

        setLayout(new org.jdesktop.swingx.VerticalLayout());

        jXButton1.setText(org.openide.util.NbBundle.getMessage(WheelPanelContent.class, "WheelPanelContent.jXButton1.text")); // NOI18N
        add(jXButton1);

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jXPanel1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    // End of variables declaration//GEN-END:variables
}
