/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WheelPanelContainer.java
 *
 * Created on 20/12/2010, 22:04:16
 */
package com.jme3.gde.jmeguiforms;

import com.jme3.gde.jmeguiforms.event.WheelPanelContentEvent;
import com.jme3.gde.jmeguiforms.event.WheelPanelContentListener;
import com.jme3.gde.jmeguiforms.event.WheelPanelListener;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Glauco
 */
public class WheelPanelContainer extends javax.swing.JPanel {

    private List<WheelPanelContentListener> listeners;
    private List<WheelPanel> children;

    /** Creates new form WheelPanelContainer */
    public WheelPanelContainer() {
        initComponents();
        listeners = new ArrayList<WheelPanelContentListener>();
        children = new ArrayList<WheelPanel>();
    }

    public WheelPanel addWheelPanel(String wheelNameValue) {
        WheelPanel panel = new WheelPanel().setNameValue(wheelNameValue);
        children.add(panel);
        jPanel1.add(panel);
        jPanel1.validate();
        jPanel1.repaint();
        return panel;
    }

    public WheelPanel addWheelPanel(String wheelNameValue, WheelPanelListener listener) {
        WheelPanel panel = addWheelPanel(wheelNameValue);
        panel.addWheelPanelListener(listener);
        return panel;
    }

    public void removeWheelPanel(String wheelName) {
        WheelPanel wheelPanel = getWheelPanel(wheelName);
        children.remove(wheelPanel);
        jPanel1.remove(wheelPanel);
        jPanel1.validate();
        jPanel1.repaint();
    }

    public WheelPanel getWheelPanel(String wheelName) {
        for (WheelPanel wheelPanel : children) {
            if (wheelPanel.getNameValue().equals(wheelName)) {
                return wheelPanel;
            }
        }
        return null;
    }

    public void addWheelPanelContentListener(WheelPanelContentListener listener) {
        listeners.add(listener);
    }

    public void removeWheelPanelContentListener(WheelPanelContentListener listener) {
        listeners.remove(listener);
    }

    public void cleanup() {
        listeners.clear();
        for (WheelPanel wheelPanel : children) {
            wheelPanel.cleanup();
        }
        children.clear();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXButton1 = new org.jdesktop.swingx.JXButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jXButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jme3/gde/jmeguiforms/icons/wheel.png"))); // NOI18N
        jXButton1.setText(org.openide.util.NbBundle.getMessage(WheelPanelContainer.class, "WheelPanelContainer.jXButton1.text")); // NOI18N
        jXButton1.setFocusable(false);
        jXButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });
        add(jXButton1, java.awt.BorderLayout.NORTH);
        jXButton1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(WheelPanelContainer.class, "WheelPanelContainer.jXButton1.AccessibleContext.accessibleName")); // NOI18N
        jXButton1.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(WheelPanelContainer.class, "WheelPanelContainer.jXButton1.AccessibleContext.accessibleDescription")); // NOI18N

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        // TODO add your handling code here:
        for (WheelPanelContentListener wheelPanelContentListener : listeners) {
            wheelPanelContentListener.addWheelActionPerformed(new WheelPanelContentEvent(this));
        }
    }//GEN-LAST:event_jXButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXButton jXButton1;
    // End of variables declaration//GEN-END:variables
}
